name: 'JavaScript Debug'
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: Run Action
        uses: ./ # Uses an action in the root directory