name: 'minecraft-js Debug'
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Action
    defaults:
      run:
        working-directory: ./behavior_pack
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: Build
        run: npm run publish
      - name: Tests
        run: npm run test