name: 'TypeScript Debug'
on: [push]

jobs:
  build:
    name: Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: npm install
        working-directory: ./types
      - run: npm run test
        working-directory: ./types
      - run: npm run build
        working-directory: ./types